//
//  PrivacyPolicyView.swift
//  WWTD
//
//  Created by Adrian Martushev on 6/27/24.
//


import SwiftUI

struct PrivacyPolicyView: View {
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    @EnvironmentObject var currentUser : CurrentUserViewModel
    
    var showPP : Binding<Bool>?
    
    var body: some View {
        

        VStack {
            VStack(alignment : .leading) {
                HStack(spacing: 0) {
                    Button(action: {
                        if let showPP = showPP {
                            showPP.wrappedValue = false
                        } else {
                            self.presentationMode.wrappedValue.dismiss()
                        }
                        
                        generateHapticFeedback()

                    }) {
                        Image(systemName: (showPP != nil) ? "xmark" : "arrow.left")
                            .font(Font.system(size: 16, weight: .semibold))
                            .foregroundColor(.primary)
                            .opacity(0.7)
                            .frame(width: 40, height: 40)
                    }

                    
                    Text("Privacy Policy")
                    .font(.system(size: 22, weight: .bold))
                    .foregroundColor(.primary)
                    .padding(.horizontal)
                    
                }
                .navigationTitle("")
                .navigationBarHidden(true)
                
                
                ScrollView {
                    VStack(alignment: .leading, spacing: 12) {
                        
                        Text("Last Updated: 6-12-24")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                        
                        Group {
                            Text("Welcome to Diddly, an AI-powered app that allows users to create itinerary schedules for any location, discover live events worldwide, and generate AI-powered schedules around chosen events. This Privacy Policy outlines how we collect, use, disclose, and safeguard your information when you use our iOS mobile application.")
                                .padding(.bottom)
                            
                            Text("1. Information We Collect")
                                .font(.headline)
                            
                            Text("Sign-in Information: When you sign in to Diddly using your Apple ID or Gmail account, we collect basic account information provided by these third-party authentication services, such as your email address and name.")
                            
                            Text("Usage Data: We collect information about your interactions with the App, including the events you view, attend, or create, as well as the schedules generated by our AI.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("2. How We Use Your Information")
                                .font(.headline)
                            
                            Text("To Provide Services: We use your sign-in information to create and manage your account and to communicate with you about your activities on the App.")
                            
                            Text("Improvement of Services: We analyze usage data to improve our AI algorithms, personalize user experiences, and enhance the functionality of the App.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("3. Sharing of Your Information")
                                .font(.headline)
                            
                            Text("With Third Parties: We may share anonymized and aggregated usage data with third-party partners for analytics and research purposes.")
                            
                            Text("Legal Compliance: We may disclose your information if required to do so by law or in response to valid legal requests.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("4. Data Security")
                                .font(.headline)
                            
                            Text("Security Measures: We implement industry-standard security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("5. Your Choices and Rights")
                                .font(.headline)
                            
                            Text("Account Information: You can review and update your account information at any time by logging into the App.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("6. Children's Privacy")
                                .font(.headline)
                            
                            Text("Age Limitation: Diddly is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13 years of age. If we learn that we have collected personal information from a child under age 13 without parental consent, we will delete that information promptly.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("7. Changes to This Privacy Policy")
                                .font(.headline)
                            
                            Text("Updates: We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You can see when this Privacy Policy was last updated by checking the “last updated” date displayed at the top of this statement.")
                        }
                        .padding(.bottom)
                        
                        Group {
                            Text("8. Contact Us")
                                .font(.headline)
                            
                            Text("If you have any questions about this Privacy Policy, please contact us at:")
                            Text("Email: diddlytravel@gmail.com")
                        }
                    }
                    .padding()
                }
                .navigationTitle("Privacy Policy")
                .navigationBarTitleDisplayMode(.inline)
            }
            .padding()
        }
        .background(.regularMaterial)
    }
}

#Preview {
    PrivacyPolicyView()
}

